### ISSUE TITLE
[PXC-10001][ERR_X_PROTOCOL_CLIENT] XClient of X-NIO-Client to my_polarx@127.0.0.1:32886 auth timeout

### ISSUE THREAD

**Issue by cheeloosoft** [ApsaraDB/galaxysql#34]
ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] XClient of X-NIO-Client to my_polarx@127.0.0.1:32886 auth timeout. 9987410021ns 
        at com.alibaba.polardbx.rpc.client.XClient.initClient(XClient.java:668)
        at com.alibaba.polardbx.rpc.pool.XClientPool.getConnection(XClientPool.java:422)
        at com.alibaba.polardbx.rpc.pool.XClientPool.getConnection(XClientPool.java:276)
        at com.alibaba.polardbx.rpc.pool.XConnectionManager.getConnection(XConnectionManager.java:469)
        at com.alibaba.polardbx.rpc.compatible.XDataSource.getConnection(XDataSource.java:193)
        at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.initTsoServicesX(MetaDbDataSource.java:126)
        at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.initXDataSourceByJdbcProps(MetaDbDataSource.java:171)
        at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.initMetaDbDataSource(MetaDbDataSource.java:182)
        at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.doInit(MetaDbDataSource.java:121)
        at com.alibaba.polardbx.common.model.lifecycle.AbstractLifecycle.init(AbstractLifecycle.java:43)
        at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.getInstance(MetaDbDataSource.java:463)
        at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.initMetaDbDataSource(MetaDbDataSource.java:489)
        at com.alibaba.polardbx.config.loader.ServerLoader.initPolarDbXComponents(ServerLoader.java:207)
        at com.alibaba.polardbx.config.loader.ServerLoader.load(ServerLoader.java:181)
        at com.alibaba.polardbx.config.loader.ServerLoader.doInit(ServerLoader.java:91)
        at com.alibaba.polardbx.common.model.lifecycle.AbstractLifecycle.init(AbstractLifecycle.java:43)
        at com.alibaba.polardbx.CobarConfig.initCobarConfig(CobarConfig.java:68)
        at com.alibaba.polardbx.CobarConfig.<init>(CobarConfig.java:61)
        at com.alibaba.polardbx.CobarServer.<init>(CobarServer.java:141)
        at com.alibaba.polardbx.CobarServer.<clinit>(CobarServer.java:95)
        at com.alibaba.polardbx.server.TddlLauncher.main(TddlLauncher.java:82)
[tddl.tar.gz](https://github.com/ApsaraDB/galaxysql/files/7624821/tddl.tar.gz)
[操作系统信息.txt](https://github.com/ApsaraDB/galaxysql/files/7624822/default.txt)

**Comment by zzy590** [comment]
是通过代码编译启动的吗？从信息看，mysql的32886端口应该是起来的，tcp的connect是成功的，认证超时，怀疑是协议没有选对，检查下polardbx-server/src/main/resources/server.properties中
galaxyXProtocol的配置是不是1
或者在对应启动目录的conf/server.properties
里面galaxyXProtocol的配置是不是1

没有的话直接加上
galaxyXProtocol=1

**Comment by cheeloosoft** [comment]
polardbx-server/src/main/conf/server.properties中的内容如下，有galaxyXProtocol=1
serverPort=3306
managerPort=3406
rpcPort=9090
charset=utf-8
processors=4
processorHandler=16
processorKillExecutor=128
timerExecutor=8
managerExecutor=256
serverExecutor=1024
idleTimeout=
trustedIps=127.0.0.1
slowSqlTime=1000
maxConnection=20000
allowManagerLogin=1
allowCrossDbQuery=true
**galaxyXProtocol=1**
metaDbAddr=127.0.0.1:3306
metaDbXprotoPort=13306
metaDbUser=my_polarx
metaDbName=polardbx_meta_db_polardbx
instanceId=polardbx-polardbx

### 
改了启动目录下的conf/server.properties ，在里面加上了galaxyXProtocol=1，现在启动的时候不报哪个错误了。

### 
# PolarDB-X 服务端口
serverPort=8527
# PolarDB-X RPC 端口
rpcPort=9090
 # MetaDB地址
metaDbAddr=127.0.0.1:4886
# MetaDB私有协议端口
metaDbXprotoPort=32886
# MetaDB用户
metaDbUser=my_polarx
metaDbName=polardbx_meta_db_polardbx
# PolarDB-X实例名
instanceId=polardbx-polardbx

galaxyXProtocol=1

谢谢指导！！！
